### ISSUE TITLE
some questions about training and visualization

### ISSUE THREAD

**Issue by Armorr** [PhyScene/PhyScene#21]
First of all, thank you for your excellent work. I have a few questions. When I reproduced ATISS, I encountered a few problems:

1. At the initial stage of training, the loss of the model in the verification set decreased, but later rose to 30-40+ and could not be controlled. This problem was mentioned in [https://github.com/nv-tlabs/ATISS/issues/20](https://github.com/nv-tlabs/ATISS/issues/20), which may be due to the new version of 3D-FRONT data set or other reasons. Have you encountered similar problems when comparing methods? If so, how did you resolve it.

2. Rooms visualized with simple-3dviz often lose textures, is it possible to avoid this problem with the remeshed dataset you provide.

3. What is your epoch and training time when you trained ATISS.

I would be grateful if you could reply and thank you again for your work in the field!

**Comment by YandanYang** [comment]
Hi ZhangYao,

Thank you for your interest in our work.

For question 1 and 3, we just follow the code and config of ATISS when
running the experiment.
For question 2, we also found the loss of texture using simple_3dviz,
but we did not find any solution. Note the remeshed data will lose the
texture, since it will change the geometry. So we only use the
remeshed data to calculate collision

I hope this answer is helpful to you.

Best,
Yandan


谭张尧 ***@***.***> 于2024年12月5日周四 15:35写道：

**Comment by Armorr** [comment]
Thank you for your timely reply!
